services:
  _defaults:
    autoconfigure: true
    autowire: false

  Xirdion\MultiFileUploadBundle\Controller\MultiFileUploadController:
    public: true
    arguments:
      - '@contao.framework'
      - '@session'
      - '%kernel.project_dir%'
