services:
  _defaults:
    autowire: true
    autoconfigure: true

  Xirdion\MultiFileUploadBundle\Controller\MultiFileUploadController:
    public: true
    arguments:
      - '@contao.framework'
      - '@session'
      - '%kernel.project_dir%'
